version: "3.1"
services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            prnote:
                ipv4_address: 101.50.1.4
    frontend:
        build: frontend/
        volumes:
            - ./frontend:/frontend
        ports:
            - "4000:8080"
        expose:
            - "8080"
        command: >
            sh -c "npm install 
                    npm run serve"
        depends_on:
            - redis
        networks:
            prnote:
                ipv4_address: 101.50.1.3
networks:
    prnote:
        ipam:
            driver: default
            config:
                - subnet: 101.50.0.1/16